apiVersion: v1
kind: PersistentVolume
metadata:
  name: helm-grafana
  namespace: default
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfsroot/grafana
    server: 192.168.56.210
