apiVersion: v1
kind: PersistentVolume
metadata:
  name: helm-jenkins
  namespace: helm-jenkins
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfsroot/jenkins
    server: 192.168.56.210