#!/bin/bash

pod_status=0

function is_pod_ready()
{
    pod_name=$1
    filter_name=$2
    echo "is_pod_ready"
    echo $pod_name $filter_name
    pod=$(kubectl get pod -A | grep $filter_name |awk '{print $2 $3 $4}');
    for i in $pod;
    do
        echo $pod;
        if [ $pod==$pod_name ] ; then
           pod_status=1
           return
        fi
    done;
}


function wait_pod_ready()
{
    pod_name=$1
    echo $1 $2
    while((1))
    do
        is_pod_ready $pod_name $2
        if [ $pod_status -eq 1 ] ; then
            echo "pod ready"
            break
        fi
        sleep 5
        echo "wait $2 ready"
    done
}

echo "start waiting sm";
wait_pod_ready "v4-virtio-sm-jian-01/1Running" "sm"
pod_status=0
echo "start waiting cuvnf";
wait_pod_ready "v4-virtio-cuvnf-jian-02/2Running" "cuvnf"
echo "all pods are ready"

function is_pod_terminated()
{
    pod_name=$1
    filter_name=$2
    echo "is_pod_terminated"
    echo $pod_name $filter_name
    pod=$(kubectl get pod -A | grep $filter_name |awk '{print $2}');
    for i in $pod;
    do
        echo $pod;
        echo "judge return 0";
        if [[ $pod==$pod_name ]] ; then
           echo "return 0"
           return 0
        fi
    done;
    echo "return 1";
    return 1
}

function wait_pod_terminated()
{
    pod_name=$1
    echo $1 $2
    while((1))
    do
        is_pod_terminated $pod_name $2
        is_pod_term=$?
        if [ $is_pod_term -eq 1 ] ; then
            echo "pod terminated"
            break
        fi
        sleep 5
        echo "wait $2 terminated"
    done
}

echo " waiting sm terminated ";
wait_pod_terminated "v4-virtio-sm-jian-0" "sm"
echo "waiting cuvnf terminated";
wait_pod_terminated "v4-virtio-cuvnf-jian-0" "cuvnf"
echo "all pods are terminated"
