apiVersion: v1
kind: PersistentVolume
metadata:
  name: helm-pqadmin
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfsroot/pqadmin
    server: 192.168.56.210
