apiVersion: v1
kind: PersistentVolume
metadata:
  name: helm-my-psql
  namespace: default
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfsroot/psql
    server: 192.168.56.210
